### ISSUE TITLE
Would it be possible to add a limit to the speed function?

### ISSUE THREAD

**Issue by jrmoore** [visualboyadvance-m/visualboyadvance-m#339]
This is a feature request rather than a bug report, I think the provided form for bug reports doesn't apply but let me know if you need to know anything else.

I downloaded the current 64-bit build for Windows after many years of not playing and I'm glad for new cross-OS UI, but since I'm now playing in a vastly more powerful machine than before and I'm sure compiler optimizations have also got better with the years, the emulation speed is nuts when in speed mode.

Normally it runs fine at 100% @ 60 FPS even with pixel filters enabled, but it jumps to 3000+% while in turbo mode. I looked if there was a way to limit it to a certain % but I couldn't see any option anywhere.

Would it be possible to implement it? If so, please consider it for a future release.

PS. Thanks for the awesome work guys & gals! Revisiting my youth has never been better ^_^

**Comment by rkitover** [comment]
Hi, go to:

Options -> General

you will see a Throttle setting, you can set it to any speed where 100% is normal speed.

HTH

**Comment by rkitover** [comment]
Ok I understand you'd like to be able to set a custom throttle for the turbo button, I think we can do this easily.

**Comment by rkitover** [comment]
Ok it was not as easy as I thought, but I implemented it in master. Maybe @ZachBacon will push a new nightly for you to try soon.

**Comment by rkitover** [comment]
@jrmoore please try this binary and see if the new `Speedup / Turbo` configuration suits your needs:


[visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/2825878/visualboyadvance-m.zip)

**Comment by retro-wertz** [comment]
> 
> 
> @jrmoore please try this binary and see if the new `Speedup / Turbo` configuration suits your needs:
> 
> [visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/2825878/visualboyadvance-m.zip)

tested using this on windows 10:
- Gameboy games are not smooth anymore (seem like frameskip is enabled)
- Speedup throttle above 450% freezes vbam to oblivion
- I still dont get what frame skip is suppose to do or even why. at setting 1, this speeds up the game at a random rate, currently on gba summon night its already speeding up game at 1000% based on status bar.
- i think you said that throttle and the frame skip is suppose to go with each other, but changing one forces the other to none or zero 

for whats is worth, fast forwarding frames is not suppose to sound like chipmunks, so that throttle option is probably doing something different thats causing sound pitch change (please try to compare with other emus since we seem to not on the same understand what the "word" is suppose to mean or do)

**Comment by rkitover** [comment]
gameboy games are exactly the same, my code has no effect on this, and I just tested this, unless someone else did anything to my code that I don't know about

see the code in GB.cpp and GBA.cpp

throttle controls sound speed, in vbam game speed is controlled by the sound driver, that's why the sound pitch changes. It should be EXACTLY the same as setting throttle in the general config pane. This is for smaller adjustments like 125%, 150%, 200% etc.. If your hardware/drivers cannot push the game at that speed, it won't go that fast.

when frame skip is enabled, that turns on speedup which is the same as throttle=0, which means the sound driver is not controlling speed anymore but dropping any excess sound data, and frames are also skipped. You could try e.g. throttle=0 frame_skip=0 to see what just having speedup on would do.

I don't know about other emus, I did what is reasonably simple to do in this one.

**Comment by retro-wertz** [comment]
what are you talking about someone change your code? like what i said, i tested windows using the link you game. recompiling vbam has the same behavior. dunno how you tested it. but i dont think you believed on any of my testings so ill just leave it up to you from now on what to do with this.

**Comment by rkitover** [comment]
What I was using for testing is the opening animation in advance wars, you can try any animation sequence for this. 150% is 150%,, the pitch changes and the animation speed changes. How would you expect the pitch to change but the game speed to not change?

**Comment by rkitover** [comment]
Note for anyone trying this, for speedup throttle to work **DISPLAY FILTER MUST BE OFF**. Otherwise the game speed will not increase. I'm going to try to fix this.

**Comment by rkitover** [comment]
moving related discussion to #404
