### ISSUE TITLE
Gamepad problems in VisualBoyAdvance-M v2.1.1

### ISSUE THREAD

**Issue by Cibomatto2002** [visualboyadvance-m/visualboyadvance-m#374]
In VisualBoyAdvance-M v2.1.0 the gamepad was working correctly. In VisualBoyAdvance-M v2.1.1 when setting up the game pad if you press left and let go keeps going left or if you press right and let go keeps going right.

Windows 10 64bit

Here is my Configuration settings file if you need it.
[vbam.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/2907895/vbam.zip)

Here is what kind of gamepad I have. 

https://www.amazon.com/gp/product/B01GDKXMPA/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1

**Comment by retro-wertz** [comment]
please fill up the template... and write if you are using the analog stick for movement, and see if using the d-pad has the same problems 

(analog stick and analog triggers are still wonky but sticks could still work with higher deadzone)

**Comment by Cibomatto2002** [comment]
I don't see a template anymore to fill out sorry The d-pad works correct. I was using the analog stick when  I sent in the bug.

**Comment by retro-wertz** [comment]
template is still here when creating new post..

anyways thanks for the confirmation. analog sticks and trigger together with keyboard modifiers needs some work and we are already aware of that.

**Comment by Squall-Leonhart** [comment]
This reproduces on a keyboard too strangely enough, might be emulator priority level related.

**Comment by LazyBunny** [comment]
I'm also having this issue on 2.1.1, using a GPD Win2. The Dpad works fine, though it has a little bit of latency issues. But the analog stick is certainly not working.

**Comment by rkitover** [comment]
Please try this binary and report your results:

[visualboyadvance-m-Win-64bit.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/3030539/visualboyadvance-m-Win-64bit.zip)

**Comment by LazyBunny** [comment]
@rkitover  The Analog is fixed for up/down/left/right in this beta version.
But there's a new issue with it. When i set a specific turbo limit, IE 500%. My turbo button no longer works. However is the turbo limit is set to 0, the turbo button/function works as normal.

Which was the most anticipated feature for 2.1.1 for me anyways. Since at 800-900% it's a bit hard to control, but at 500% or so i can react quickly enough. (When walking around in pokemon.)

**Comment by rkitover** [comment]
@LazyBunny I've hard reports that the speedup button configuration does not work for some people, and I noticed it hasn't worked for me on occasion as well, I don't know why yet. Could you try some things:

- try turning off display filter or turning it on (to e.g. xbrz6)
- try switching sound driver
- see if the normal throttle setting behaves the same way

This may be linked to a memory error of some sort, I will try to do more debugging.

**Comment by LazyBunny** [comment]
Ok Using OpenGL backend. Moemon Emerald 4x mag. VBA-M 2.1.1-d66e8108
"OR implies multiple tests with each of the OR settings"

SDL, No Filter OR simple 4x OR xbrz6, 500% Turbo cap, freeze/Hardlock of VBA-M

Xaudio2 No stereo upmixing, no filter, 500% turbo, works**
**I can't get above 400% turbo with no display filter, xaudio is hard on my system.
But i can't go above 350% with Simple 4x. If i set the turbo cap to 300%, it'll hover between 292 and 302%

DirectSound-Hardware Acc On or off, No Filter or Simple 4x, 500% turbo cap, Not working.

I generally use DirectSound With hardware Acceleration as i can hit about 800-900% turbo speeds. So a 500% cap would be very light on my system.
GPD Win2
2.4ghz m3-7y30
8GB DDR3LP
256GB-SSD
128GB USB3 Samsung Fit (contains my emulators including Gameboy, about 80MB read, 35MB write, but fairly weak IOPS for a thumb drive)

Intel HD 615, capped at about 850mhz for some stupid reason. I have a fully unlocked bios control but i can't seem to do anything with this thing. I can't even make it run at 850mhz 100% of the time when i need it to the most.

**Comment by rkitover** [comment]
@LazyBunny thank you for testing, so if I understand correctly with xaudio2 the speedup configuration let you go up to around 400% throttle, but with other sound drivers it did not work.

Can you please test one other thing for me, go into the `General` config and set the normal `throttle` value instead of the speedup key and see if you get the same results.

Thank you!

**Comment by LazyBunny** [comment]
Xaudio2, throttle cap 0, General throttle 900%(to let it go as fast as it can)
No graphics filter ~400%, it spiked to 425%
Simple 4x filter, ~350%.
So same.

XAudio2 on is just hard on this system. Same results with 2.1.0
It's why i use DirectSound.

Which i just remembered, may have NOTHING to do with VBA-M.
Some GPD-Win2's have an audio polarity bug, which require a software work-around to correct the phase polarity. And that work-around may be causing a massive performance hit when used with Xaudio2. And disabling this workaround is... not something i'm going to test, it wasn't fun setting it up.
https://www.reddit.com/r/gpdwin/comments/8tr0ws/how_to_fix_reversed_audio_polarity_via_software/?st=ju0irsfn&sh=55ea4884

**Comment by rkitover** [comment]
@LazyBunny thank you.

Can you confirm that the throttle setting behaves the same way as the speedup key setting when using throttle for the speedup key (meaning **NOT** frame skip.) With the sound drivers you tested but setting throttle instead of speedup key.

This is what I need to know.

If this is true, we can focus on fixing throttle as unrelated to this feature.

**Comment by LazyBunny** [comment]
I never use frame skip, ever. Throttle implies Throttle menu within General Settings, Turbo cap always implies the Turbo menu, used with the turbo key**
No GFX Filter.
SDL, Throttle (Not Turbo key), Starts, runs 200%, 300%, 400%
SDL, Throttle (Not Turbo key), freeze on start, have to hard close(not responding) at 500% and 600%

XAudio2, Throttle(not turbo key), works fine, at 200%+, but still can't go above 400%.

Directsound... Ok this one is a bit of a mess on this version of 2.1.1. Whew.. Okay we're in for a wild ride here.
**Directsound, Hardware Acceleration ON, Turbo set to 0, Throttle(in general) set to 600%... I can't go above ~320%. Turbo/speedup key does nothing.(this is important)

Directsound, Hardware Acceleration OFF, Turbo set to 0, Throttle(in general) set to 600%... game runs at 100%, from the start... Turbo/speedup key goes to ~320% to 340%.
Turbo is set to 0%, Throttle is set to 600%


2.1.0 Direct sound, HW Acc On, throttle @100%, turbo key lets me hit 800% to 900%
This 2.1.1beta is giving me like, 40% performance, when it's working. Though i totally get that it's a beta, so there's lots of bugs.

**Comment by rkitover** [comment]
@LazyBunny thanks, but I'm still not sure what's happening here. The binary I posted here was built the same way as the 2.1.1 release, and 2.1.0 does not have a configurable turbo feature, only 2.1.1 does.

So did you notice a difference between the speedup key and setting throttle in the general config?

On 2.1.0 the speedup key skips 9 frames, the effect should be the same as selecting 9 frames to skip for the speedup key config, this has always been the default.

**Comment by LazyBunny** [comment]
@rkitover OHH I get what you mean. Then that would be my confusion! My mistake completely, i understand you now. That would explain the 900%. Then nevermind on the speed/performance, since there was no turbo/speedup menu on 2.1.0. The freezes and crashes are still relevant for SDL, and the weird behavour with directsound with HW Acc on vs off though. Since in 2.1.1b in the turbo menu, i did specifically set the speedup frameskip to 0.

I'll go through, reset all my .ini's and test them all again with different configs and document the different behaviors this afternoon.

I was under the impression 2.1.0 just let it run as fast as it could. Without frame skip. Since no menu for it in 2.1.0(that i found), i didn't see a frameskip option.
 Which when testing it in no throttle, DOES match up with the performance i was having in 2.1.1b so about 350-400% or so.

I refer to the speedup key as the turbo key.

**Comment by rkitover** [comment]
@LazyBunny 

Let me explain how the turbo configuration works.

There are three possible states when the turbo button is pressed, throttle, speedup and speedup with frame skip.

If you select zero throttle and zero frame skip, then speedup is in effect, the game runs at full speed without skipping frames.

If you select a number of frames to skip, then speedup is in effect, the game runs at full speed and ALSO skips that number of frames, the default is/was 9 frames.

If you select throttle, speedup is NOT in effect, and the sound driver syncs the game to that percentage of game speed, the game speed is always synced by the sound driver regardless.

**Comment by LazyBunny** [comment]
@rkitover 
2.1.1b Sorry, it's a lot of info to di through. Decided to redo the tests.  Weird stuff bolded
Default settings:OpenGL, Speedup Frameskip 0, Auto Frameskip off, No Display Filter, Multithread filter on, 4x mag, no bios
Turbo refers to speedup key. (Not frameskip.) 440% is my general average, It actually bounces between 420 and 460. It's not a solid 440, but i see 44x the most.
Rom Moemon Emerald US, GBA.

SDL 44.1khz
Turbo set to 0.
SDL, Throttle No Cap(None), starts runs normal at about ~440%
SDL, Throttle Cap ranging from 100%, 200%, 300%, 400%, Starts runs normal at their respective caps.
**SDL**, Throttle cap, 500%, 600%, and higher. Freeze on rom load.

Throttle set to 100%
SDL, Turbo No Cap 0%, Starts, runs normal at 100%, Speedup key turbos to about ~440%
Lazy: Increasing Turbo cap to 200%, 300%, while game is still running, works as expected. Was lazy for these 2.
SDL, Turbo 400%, Starts, runs normal at 100%, Speedup key turbos to about 400%, works as expected
SDL, Turbo 450%, Starts, Runs normal at 100%, speedup key turbos to about ~440%, as expected. My cap it would appear.
**SDL**, Turbo 500%, Starts normal, Freezes on Turbo button press.

I'm starting to wonder if the 500%+ is crashing because my system can't come close to 500%? Or if it's something else entirely. I exclusively use my GPD Win2 for emulation for anything Wii/PS2 and older.

DirectSound 44.1khz
Turbo set to 0%
No Hardware Acceleration
DS, Throttle Cap set to None, Starts runs at about ~440% same as SDL it seems.
DS, Throttle Cap set to 200% OR 400%, Starts, runs at 200% and 400% respectively as expected.
DS, Throttle Cap set to 450%, Starts, runs at 440%.
Now we get the weird stuff. Still this is with No Hardware Acceleration.
**DS**, Throttle Cap set to 500% OR 600%, Turbo Cap 0%, Starts, runs at 100%. Pressing Turbo goes to ~440%, releasing returns to 100%.
**DS**, Throttle Cap set to 500% OR 600%, Turbo Cap set to 300%, Starts at 100%, pressing Turbo once, locks it at 300%. Does not stop running at 300% when turbo is released.

Throttle set to 100%
DS, Throttle cap 100%, Turbo at 0%, starts at 100%, turbos to 440%
Lazy: While game is running, increase turbo cap to 200%, 300%, 400%, acts as expected, turbos to 200%,300%,400% as expected.
Setting turbo to 450%, goes to about 440%, my expected result.

**DS**, Turbo set to 500% to 600%, game starts at 100%, turbo key does nothing.

DirectSound 44.1khz
Hardware Acceleration Enabled
Turbo Cap set to None,
DSHWAC, Throttle Cap set to Non, Turbo Cap set to None. Game starts and runs at ~440%
DSHWAC, Throttle cap 100%, 200%, 300%, 400%, Turo cap 0%, Game starts at 100%,200%,300%,400% as Expected. Turbos to ~440% when turbo key is pressed, works as expected.
And the weird stuff.
**DSHWAC**, Throttle Cap set to 500%,600%, Turbo Cap 0%, Game starts at 100%. Turbo key goes to 440%, returns to 100% on release.
**DSHWAC**, Throttle cap set to 500,600, Turbo Cap 300%, Game starts at 100%, Turbo key goes to and locks at 300%, does not return to 100%
**DSHWAC**, Throttle Cap 500%-600%, Turbo Cap 500%-600%, Game starts at 100%, turbo key does nothing. Remains at 100%

DSHWAC, Throttle Cap 100%, Turbo Cap 200%, 300%, 400%, 450%, Game starts at 100%, turbos to 200%, 300%, 400%, 440% as expected.
**DSHWAC**, Throttle Cap 100%, Turbo Cap 500% or 600%, Game starts at 100%, turbo key does nothing.


XAudio2 44.1khz
All without stereo upmixing. Because i have no idea what it does, also i'm getting bored.

XA2, Throttle Cap 0%, Turbo cap 0%, Game starts and runs at ~440%
XA2, Throttle Cap at 100%, 200%, 300%, 400%, Turbo Cap 0%. Game Starts and runs at 100%, 200%, 300%, 400%, as expected, turbos to 440%.
**XA2**, Throttle cap set to 450%, 500%, 600%, turbo cap 0%, Game starts and runs at 400%, turbos to ~440%. This is weird, it's not freezing or anything, it's just capping at 400% throttle. Turbo works as expected to ~440%

**Weird stuff:**
While attempting to set the throttle cap too 100%, turbo cap to 200%, to run my Turbo tests. I noticed my turbo was only hitting 380%. Some how, while changing my caps, just now, 2xSAL keeps getting added to the Graphics filter and it keeps re-adding itself, and disabling my Multithread Filter until i restarted the emulator.

After finally getting my settings corrected, the 2xSAL filter off,  and Multithread Filter enabled again.
XA2, Throttle cap 100%, Turbo Cap 200%, 300%, 400%, Game starts at 100%, turbos to 200%, 300%, 400%, runs as expected.
**XA2**, Throttle Cap 100%, Turbo Cap 450%, 500%, 600%, Game starts at 100%, Turbos to 400%. Does not go above 400%.
**Weird stuff:** Setting Turbo cap back to 0% disabled my Multithread Filter.
Backtracking:
XA2, Throttle Cap 100%, Turbo Cap 0%, Game Starts at 100%, Turbos to about 440% as expected.

**Comment by Cibomatto2002** [comment]
it's working properly now.

**Comment by LazyBunny** [comment]
@Cibomatto2002 Yeah, the Analog movement is. We kinda Hijacked your thread for another issue, that happened to occur in that new version. Which has something to do when throttle/turbos are set to 500% or higher.

**Comment by Cibomatto2002** [comment]
I left it open because I seen it was Hijacked.

**Comment by rkitover** [comment]
@LazyBunny thank you very much for this very extensive test run.

Things seem to be working like I expected, pretty much, with occasional glitches, for which I will create a separate thread.

As for the original issue, I posted an updated nightly with the fix and I will do a new release as soon as possible.

**Comment by rkitover** [comment]
moving speedup related issues to #404

**Comment by rkitover** [comment]
fix released in v2.1.2

**Comment by qes-fhliew** [comment]
Hello @rkitover , good day to you.
Recently I downloaded the version 2.1.5, still having the DPAD issue. While I try to map the DPAD button is refers to "Joy1-Button13, 14 ,15 and 16", but in version 2.1.1 that you shared on thread above it successfully mapped to "Joy1-Hat0N, Joy1-Hat0S, Joy1-Hat0E, Joy1-Hat0W" and these is working completely fine without keep spamming the keys.. I try to copied the text "Joy1-Hat0N" and paste to the textbox into the key mapping for direction, it did not seem any error as it can saved/reload...just that it did not function if I did this way....you reply will be highly appreciated! thanks!

**Comment by Squall-Leonhart** [comment]
the newer version of SDL doesn't have your controller use hat switches.

**Comment by Steelskin** [comment]
Newer versions of SDL treat the d-pad input as buttons. Is something not working when you save the directional input as buttons 13, 14, 15 and 16?

**Comment by qes-fhliew** [comment]
@Steelskin Hi :) Yes when it detected as buttons, it keep trigger the direction i.e I pressed Left once, it keep going Left without stop

**Comment by Squall-Leonhart** [comment]
typically caused by interference, or a system that is already heavily overloaded cpu wise.

**Comment by Steelskin** [comment]
@qes-fhliew 
Can you file a new bug with details about your hardware configuration and which controller you are using?

**Comment by Achampnator** [comment]
I can't use any of my Controller on version 2.2.2 help me!
