### ISSUE TITLE
(Post r1229 regression)Croket 2 slowdown going left of the snowman at start of game.

### ISSUE THREAD

**Issue by Squall-Leonhart** [visualboyadvance-m/visualboyadvance-m#804]
It looks like when Normmatt resolved the hang issue in this specific location, he broke 8bit memory loads causing them all to be 32bit, going by the change set here https://sourceforge.net/p/vbam/code/1205/tree//trunk/src/gba/GBAinline.h?diff=51a5080727184674d4b548ec:1204

MGBA does not choke in this location whilst encountering "bad" memory load8 and 32's at this location.

**Comment by Squall-Leonhart** [comment]
@endrift does this seem accurate or did you do something differently in this case?

even no$gba encounters a slowdown here.

**Comment by endrift** [comment]
This commit doesn't look correct. First of all, 15 (which I am assuming correlates with 0x0Fxxxxxx) is _not_ mapped. Second, this does not handle unaligned 16-bit reads properly. NO$GBA may or may not handle those correctly either, I'm not sure. I do know that its GBA emulation is pretty lacking in fixes over the last 8 years since I began investigating edge cases, so it being broken isn't really surprising here.

**Comment by Squall-Leonhart** [comment]
I just realised this was actually working fine in 1229, and no amount of changes to gbainline or using a particular svn copy will fix it, so the issue is likely in the gba.cpp or one of the arm files.

**Comment by Squall-Leonhart** [comment]
https://sourceforge.net/p/vbam/code/1232/tree//trunk/src/gba/GBAinline.h?diff=1226

i broke this (doh!) but i could have sworn i tested to see if croket2 was still working,  maybe not.

**Comment by Squall-Leonhart** [comment]
I found my mistake.......

and its a single line, 6 character mistake.

**Comment by Squall-Leonhart** [comment]
@rkitover can you add a new line here before //  default and add break;

https://github.com/visualboyadvance-m/visualboyadvance-m/blob/b0c029a3893b0cebdddb0736404eed56d0901662/src/gba/GBAinline.h#L291

**Comment by rkitover** [comment]
Fixed by @Squall-Leonhart in b50ff85, running new nightly now.

**Comment by rkitover** [comment]
New nightly generated, thanks @Squall-Leonhart, I'm going to try to get mac nightlies going tonight.

**Comment by endrift** [comment]
This doesn’t fix the other two issues I directly brought up in my earlier reply.

**Comment by Squall-Leonhart** [comment]
will open a new bug for those, though i'm not sure about the mapping of 15 in current code, 

this issue was to make croket work again how normmatt last left it.
